#!/usr/bin/env python
# license removed for brevity
import rospy
import math
import numpy
from geometry_msgs.msg import Point
import time

#For a circle with origin (j, k) and radius r:
#x(t) = r cos(t) + j
#y(t) = r sin(t) + k

