#!/usr/bin/env python
# license removed for brevity
import rospy
import math
from sibot_msgs.msg import Servo_Array
from geometry_msgs.msg import Vector3

#Arm parameters
L2 = 150 # [cm], Second link lenght
L3 = 150 # [cm], Third link lenght

pub = rospy.Publisher('resP', Vector3, queue_size=10)

def callback(joints):
    # Desired joints:
    angles = [joint*math.pi/180 for joint in joints.data]    # Desired position,cylindrical coordinates
    # Resulting position:
    angles[1] = math.pi - angles[1]
    r = L2*math.cos(angles[1])+L3*math.cos(angles[2]-angles[1]+math.pi/2-math.pi+angles[1]) 
    x = r*math.cos((angles[0]-math.pi/2)/2)
    y = r*math.sin((angles[0]-math.pi/2)/2)
    z = L2*math.sin(angles[1])+L3*math.sin(angles[2]-angles[1]+math.pi/2-math.pi+angles[1]) 
    pub.publish(x,y,z)

def listener():
    rospy.init_node('servo2pos', anonymous=True)
    rospy.Subscriber("servo", Servo_Array, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()
